#!/bin/bash

#部署lnmp环境

yum -y install gcc pcre-devel zlib-devel openssl-devel
scp student@192.168.4.254:/linux-soft/03/Zabbix/* /root/
tar -xf /root/nginx-1.12.2.tar.gz
cd /root/nginx-1.12.2/
./configure --with-http_ssl_module
make && make install
yum -y install php php-mysql mariadb mariadb-devel mariadb-server
yum -y install php-fpm

#修改nginx配置文件
sed -i    '65,71s/#//' /usr/local/nginx/conf/nginx.conf
sed -i    '69s/^/#/' /usr/local/nginx/conf/nginx.conf
sed -i    '70s/fastcgi_params/fastcgi.conf/' /usr/local/nginx/conf/nginx.conf

#启动服务
systemctl start mariadb
systemctl start php-fpm
/usr/local/nginx/sbin/nginx
systemctl enable mariadb
systemctl enable php-fpm
echo "/usr/local/nginx/sbin/nginx" >> /etc/rc.local
chmod +x /etc/rc.local

#安装源码zabbix
cd;tar -xf zabbix-3.4.4.tar.gz
yum -y install net-snmp-devel curl-devel libevent-devel
cd /root/zabbix-3.4.4/ || exit 1
./configure  --enable-server --with-mysql=/usr/bin/mysql_config --enable-proxy --enable-agent --with-net-snmp --with-libcurl
make install || exit 2
ls /usr/local/bin/ /usr/local/sbin/ /usr/local/etc/
mysql -e 'create database zabbix character set utf8'
mysql -e "grant all on zabbix.* to zabbix@localhost identified by 'zabbix'"
cd /root/zabbix-3.4.4/database/mysql/
mysql -uzabbix -pzabbix zabbix < schema.sql
mysql -uzabbix -pzabbix zabbix < images.sql 
mysql -uzabbix -pzabbix zabbix < data.sql 
mysql -uzabbix -pzabbix zabbix -e "use zabbix;show tables"
cd /root/zabbix-3.4.4/frontends/php/
cp -a * /usr/local/nginx/html/
chmod -R 777 /usr/local/nginx/html/*
sed -i '17a fastcgi_buffers 8 16k ; ' /usr/local/nginx/conf/nginx.conf
sed -i '17a fastcgi_buffers_size 32k; ' /usr/local/nginx/conf/nginx.conf
sed -i '17a fastcgi_connect_timeout 300 ; ' /usr/local/nginx/conf/nginx.conf
sed -i '17a fastcgi_send_timeout 300 ; ' /usr/local/nginx/conf/nginx.conf
sed -i '17a fastcgi_read_timeout 300 ; ' /usr/local/nginx/conf/nginx.conf
yum -y install php-gd php-xml php-ldap
yum -y install php-bcmath php-mbstring
